var appData = {};

appData.statesList = [
	{
		stateName	:"Uttar Pradesh",
		stateCode	:"up",
		datesS		:[
		],
		cities		:[
			{
			   "cityName":"Agra",
			   "cityCode":"agra",
			   "datesC":[],
			},
			{
			   "cityName":"Aligarh",
			   "cityCode":"aligarh",
			   "datesC":[],
			},
			{
			   "cityName":"Amroha",
			   "cityCode":"amroha",
			   "datesC":[],
			},
			{
			   "cityName":"Auraiya",
			   "cityCode":"auraiya",
			   "datesC":[],
			},
			{
			   "cityName":"Ayodhya",
			   "cityCode":"ayodhya",
			   "datesC":[],
			},
			{
			   "cityName":"Azamgarh",
			   "cityCode":"azamgarh",
			   "datesC":[],
			},
			{
				"cityName":"Badaun",
				"cityCode":"badaun",
				"datesC":[],
			},
			{
			   "cityName":"Baghpat",
			   "cityCode":"baghpat",
			   "datesC":[],
			},
			{
			   "cityName":"Bahraich",
			   "cityCode":"bahraich",
			   "datesC":[],
			},
			{
			   "cityName":"Balrampur",
			   "cityCode":"balrampur",
			   "datesC":[],
			},
			{
			   "cityName":"Banda",
			   "cityCode":"banda",
			   "datesC":[],
			},
			{
			   "cityName":"Bara Banki",
			   "cityCode":"baraBanki",
			   "datesC":[],
			},
			{
			   "cityName":"Bareilly",
			   "cityCode":"bareilly",
			   "datesC":[],
			},
			{
			   "cityName":"Basti",
			   "cityCode":"basti",
			   "datesC":[],
			},
			{
			   "cityName":"Bhadohi",
			   "cityCode":"bhadohi",
			   "datesC":[],
			},
			{
			   "cityName":"Bijnore",
			   "cityCode":"bijnore",
			   "datesC":[],
			},
			{
			   "cityName":"Bulandshahr",
			   "cityCode":"bulandshahr",
			   "datesC":[],
			},
			{
			   "cityName":"Etah",
			   "cityCode":"etah",
			   "datesC":[],
			},
			{
			   "cityName":"Etawah",
			   "cityCode":"etawah",
			   "datesC":[],
			},
			{
			   "cityName":"Firozabad",
			   "cityCode":"firozabad",
			   "datesC":[],
			},
			{
			   "cityName":"Gautam Buddha Nagar",
			   "cityCode":"gautamBuddhaNagar",
			   "datesC":[],
			},
			{
			   "cityName":"Ghaziabad",
			   "cityCode":"ghaziabad",
			   "datesC":[],
			},
			{
			   "cityName":"Ghazipur",
			   "cityCode":"ghazipur",
			   "datesC":[],
			},
			{
			   "cityName":"Gonda",
			   "cityCode":"gonda",
			   "datesC":[],
			},
			{
			   "cityName":"Gorakhpur",
			   "cityCode":"gorakhpur",
			   "datesC":[],
			},
			{
			   "cityName":"Hapur",
			   "cityCode":"hapur",
			   "datesC":[],
			},
			{
			   "cityName":"Hardoi",
			   "cityCode":"hardoi",
			   "datesC":[],
			},
			{
			   "cityName":"Hathras",
			   "cityCode":"hathras",
			   "datesC":[],
			},
			{
			   "cityName":"Jalaun",
			   "cityCode":"jalaun",
			   "datesC":[],
			},
			{
			   "cityName":"Jaunpur",
			   "cityCode":"jaunpur",
			   "datesC":[],
			},
			{
			   "cityName":"Jhansi",
			   "cityCode":"jhansi",
			   "datesC":[],
			},
			{
			   "cityName":"Kannauj",
			   "cityCode":"kannauj",
			   "datesC":[],
			},
			{
			   "cityName":"Kanpur Nagar",
			   "cityCode":"kanpurNagar",
			   "datesC":[],
			},
			{
			   "cityName":"Kasganj",
			   "cityCode":"kasganj",
			   "datesC":[],
			},
			{
			   "cityName":"Kaushambi",
			   "cityCode":"kaushambi",
			   "datesC":[],
			},
			{
			   "cityName":"Lakhimpur",
			   "cityCode":"lakhimpur",
			   "datesC":[],
			},
			{
			   "cityName":"Lucknow",
			   "cityCode":"lucknow",
			   "datesC":[],
			},
			{
			   "cityName":"Maharajganj",
			   "cityCode":"maharajganj",
			   "datesC":[],
			},
			{
			   "cityName":"Mainpuri",
			   "cityCode":"mainpuri",
			   "datesC":[],
			},
			{
			   "cityName":"Mathura",
			   "cityCode":"mathura",
			   "datesC":[],
			},
			{
			   "cityName":"Mau",
			   "cityCode":"mau",
			   "datesC":[],
			},
			{
			   "cityName":"Meerut",
			   "cityCode":"meerut",
			   "datesC":[],
			},
			{
			   "cityName":"Mirzapur",
			   "cityCode":"mirzapur",
			   "datesC":[],
			},
			{
			   "cityName":"Moradabad",
			   "cityCode":"moradabad",
			   "datesC":[],
			},
			{
			   "cityName":"Muzaffar Nagar",
			   "cityCode":"muzaffarNagar",
			   "datesC":[],
			},
			{
			   "cityName":"Pilibhit",
			   "cityCode":"pilibhit",
			   "datesC":[],
			},
			{
			   "cityName":"Pratapgarh",
			   "cityCode":"pratapgarh",
			   "datesC":[],
			},
			{
			   "cityName":"Prayagraj",
			   "cityCode":"prayagraj",
			   "datesC":[],
			},
			{
			   "cityName":"Rae Bareli",
			   "cityCode":"raeBareli",
			   "datesC":[],
			},
			{
			   "cityName":"Rampur",
			   "cityCode":"rampur",
			   "datesC":[],
			},
			{
			   "cityName":"Saharanpur",
			   "cityCode":"saharanpur",
			   "datesC":[],
			},
			{
			   "cityName":"Sambhal",
			   "cityCode":"sambhal",
			   "datesC":[],
			},
			{
			   "cityName":"Sant Kabir Nagar",
			   "cityCode":"santKabirNagar",
			   "datesC":[],
			},
			{
			   "cityName":"Shahjahanpur",
			   "cityCode":"shahjahanpur",
			   "datesC":[],
			},
			{
			   "cityName":"Shamli",
			   "cityCode":"shamli",
			   "datesC":[],
			},
			{
			   "cityName":"Sitapur",
			   "cityCode":"sitapur",
			   "datesC":[],
			},
			{
				"cityName":"Srawasti",
				"cityCode":"srawasti",
				"datesC":[],
			 },
			{
			   "cityName":"Sultanpur",
			   "cityCode":"sultanpur",
			   "datesC":[],
			},
			{
			   "cityName":"Unnao",
			   "cityCode":"unnao",
			   "datesC":[],
			},
			{
			   "cityName":"Varanasi",
			   "cityCode":"varanasi",
			   "datesC":[],
			}
		]
	}
];

appData.formDataPayload = {
	"date":"20200327",
	"state":"up",
	"citiesFormData":[
	   {
		  "cityCode":"agra",
		  "data":{
			 "total":10,
			 "totalActive":3,
			 "totalRecovered":7,
			 "totalDeaths":0,
			 "newCaseCount":2,
			 "newRecoveredCount":7,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"aligarh",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"amroha",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"auraiya",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"ayodhya",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"azamgarh",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"badaun",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"baghpat",
		  "data":{
			 "total":1,
			 "totalActive":1,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":1,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"bahraich",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"balrampur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"banda",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"baraBanki",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"bareilly",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"basti",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"bhadohi",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"bijnore",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"bulandshahr",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"etah",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"etawah",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"firozabad",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"gautamBuddhaNagar",
		  "data":{
			 "total":18,
			 "totalActive":7,
			 "totalRecovered":4,
			 "totalDeaths":0,
			 "newCaseCount":null,
			 "newRecoveredCount":null,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"ghaziabad",
		  "data":{
			 "total":5,
			 "totalActive":3,
			 "totalRecovered":2,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"ghazipur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"gonda",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"gorakhpur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"hapur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"hardoi",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"hathras",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"jalaun",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"jaunpur",
		  "data":{
			 "total":1,
			 "totalActive":1,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"jhansi",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"kannauj",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"kanpurNagar",
		  "data":{
			 "total":1,
			 "totalActive":1,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"kasganj",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"kaushambi",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"lakhimpur",
		  "data":{
			 "total":1,
			 "totalActive":1,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"lucknow",
		  "data":{
			 "total":8,
			 "totalActive":7,
			 "totalRecovered":1,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":1,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"maharajganj",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":null,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"mainpuri",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"mathura",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"mau",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"meerut",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"mirzapur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"moradabad",
		  "data":{
			 "total":1,
			 "totalActive":1,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"muzaffarNagar",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"pilibhit",
		  "data":{
			 "total":2,
			 "totalActive":2,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"pratapgarh",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"prayagraj",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"raeBareli",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"rampur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"saharanpur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"sambhal",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"santKabirNagar",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"shahjahanpur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"shamli",
		  "data":{
			 "total":1,
			 "totalActive":1,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"sitapur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"srawasti",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"sultanpur",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"unnao",
		  "data":{
			 "total":0,
			 "totalActive":0,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   },
	   {
		  "cityCode":"varanasi",
		  "data":{
			 "total":1,
			 "totalActive":1,
			 "totalRecovered":0,
			 "totalDeaths":0,
			 "newCaseCount":0,
			 "newRecoveredCount":0,
			 "newDeathsCount":0
		  }
	   }
	]
}

exports.appData = JSON.stringify(appData);